spring:
  application:
    name: sample-app
  mysql-datasource:
    driver-class-name: software.aws.rds.jdbc.mysql.Driver
    username: sample
    password: sample
    jdbc-url: jdbc:mysql://localhost:3306/sample

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    com:
      atomikos: DEBUG

hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

#  aws-mysql-datasource:
#    driver-class-name: software.aws.rds.jdbc.mysql.Driver
#    username: admin
#    password: dkakwhs1!
#    jdbc-url: jdbc:mysql://aurora-mysql.cluster-csnnojvv21on.ap-northeast-2.rds.amazonaws.com:3306/poc